version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          name: Test login with Chrome
          yarn: true
          spec: cypress/integration/login/login.feature cypress/integration/changeProfile/changeProfile.feature
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          post-steps:
            - run:
                name: generate combined report
                when: always
                command: yarn run report
            - store_artifacts:
                path: cypress/reports/html
      - cypress/run:
          name: Test login with Firefox
          yarn: true
          spec: cypress/integration/login/login.feature cypress/integration/changeProfile/changeProfile.feature
          executor: cypress/browsers-chrome78-ff70
          browser: firefox
          post-steps:
            - run:
                name: generate combined report
                when: always
                command: yarn run report
            - store_artifacts:
                path: cypress/reports/html
